# Generated by Django 2.0.7 on 2018-07-14 14:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='card_cross',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('check_detetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor', models.CharField(max_length=6)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passage_point.card')),
            ],
        ),
    ]
